sensors:
  # Bins 1-4
  logical_camera_0:
    type: logical_camera
    pose:
      xyz: [-2.286283, 2.963994, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]
  
  # Bins 5-8
  logical_camera_1:
    type: logical_camera
    pose:
      xyz: [-2.286283, -2.963994, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

  # Conveyor
  breakbeam_0:
    type: break_beam
    pose:
      xyz: [-0.900000, 4.000000, 0.921000]
      rpy: [0.000000, 0.000000, 0]
  
  logical_camera_2:
    type: logical_camera
    pose:
      xyz: [-0.500000, 3.000000, 2.000000]
      rpy: [3.141593, 1.570792, 0.000000]
  
  # Assembly stations
  depth_camera_as1:
    type: depth_camera
    pose:
      xyz: [-7.300000, 3.000000, 2.500000]  # all were 2.7 in z; changed 5/23
      rpy: ['pi/2', 'pi/2', 0]
  
  depth_camera_as2:
    type: depth_camera
    pose:
      xyz: [-12.300000, 3.000000, 2.500000]
      rpy: ['pi/2', 'pi/2', 0]
  
  depth_camera_as3b:
    type: depth_camera
    pose:
      xyz: [-7.300000, -3.000000, 2.500000]
      # xyz: [-7.600000, -2.700000, 2.600000]
      rpy: ['pi/2', 'pi/2', 0]
  
  depth_camera_as4:
    type: depth_camera
    pose:
      xyz: [-12.300000, -3.000000, 2.500000]
      rpy: ['pi/2', 'pi/2', 0]

  # AGVs at assembly stations
  logical_camera_agv1_as1:
    type: logical_camera
    pose:
      xyz: [-5.6, 4.675400, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_agv1_as2:
    type: logical_camera
    pose:
      xyz: [-10.6, 4.675400, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_agv2_as1:
    type: logical_camera
    pose:
      xyz: [-5.6, 1.367643, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_agv2_as2:
    type: logical_camera
    pose:
      xyz: [-10.6, 1.367643, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]
  
  logical_camera_agv3_as3:
    type: logical_camera
    pose:
      xyz: [-5.6, -1.333917, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_agv3_as4:
    type: logical_camera
    pose:
      xyz: [-10.6, -1.333917, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_agv4_as3:
    type: logical_camera
    pose:
      xyz: [-5.6, -4.696062, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

  logical_camera_agv4_as4:
    type: logical_camera
    pose:
      xyz: [-10.6, -4.696062, 1.801095]
      rpy: [3.141593, 1.570792, 0.000000]

# Change below to true to enable the gantry camera...not sure how useful it is, though...  
robot_camera:
  enable: false
